/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hpadcfPbkUj
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AppRouterInstance } from "next/dist/shared/lib/app-router-context.shared-runtime";
import { SignOutComponent } from "./sign-out-component";

interface HomeComponentProps {
  router: AppRouterInstance
}

export function HomeComponent({ router }: HomeComponentProps) {
  
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex justify-between items-center">
        <h1 className="text-2xl font-bold">My Stories</h1>
        <div className="flex items-center gap-4">
          <SignOutComponent />
        </div>
      </header>
      <main className="flex-1 overflow-y-auto p-6">
        <div className="mb-6 flex justify-end">
          <Button
            variant="outline"
            className="inline-flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-primary hover:text-primary-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
            onClick={() => router.push("/create-story")}
          >
            <PlusIcon className="w-5 h-5" />
            <span>Create New Story</span>
          </Button>
        </div>
        <div className="mb-6">
          <h2 className="text-xl font-bold mb-2">Recent Stories</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 1</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Action</div>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 2</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Drama</div>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 3</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Comedy</div>
              </CardContent>
            </Card>
          </div>
        </div>
        <div>
          <h2 className="text-xl font-bold mb-2">All Stories</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 4</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Romance</div>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 5</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Sci-Fi</div>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 6</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Horror</div>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 7</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Fantasy</div>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 8</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Documentary</div>
              </CardContent>
            </Card>
            <Card className="bg-card text-card-foreground">
              <CardHeader>
                <CardTitle>Story Title 9</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground">Mystery</div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}

function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
